### ISSUE TITLE
LTSSM.Config_Complete issue 

### ISSUE THREAD

**Issue by huy98no2** [wyvernSemi/pcievhost#4]
I think some miss-match about Specification of LTSSM. In Config.Complete state, TX need to send 16 TS2 and RX need to receive 8 TS2. But in C code ltssm.c, TX only send 8 TS2. You can see below picture : 
![ltssm_8ts2_send](https://github.com/wyvernSemi/pcievhost/assets/55677077/843363eb-b3df-4b0e-a8ea-3e57c8445048)
![spec_16TS2](https://github.com/wyvernSemi/pcievhost/assets/55677077/55f2f61b-fbea-4aa2-b0a2-4b9cb4867c55)

**Comment by huy98no2** [comment]
In addition, I tested with Cadence VIP, they send 16 TS2 at Cfg.Complete. My testcase is Gen1 and 1 Lane.

**Comment by wyvernSemi** [comment]
You are correct. The issue with the code is that it terminates the loop when it has _received_ 8 TS2 ordered sets, but should continue until it has sent 16. An additional counter for the number of TS2's sent is required and the loop continue if either the received count is less than 8 _or_ the sent count is less than 16.  I will update the code and retest.

**Comment by wyvernSemi** [comment]
New code is now pushed to the master branch. It now generates at least 16 TS2 in conifg.complete.

**Comment by huy98no2** [comment]
Thank you for your update !!

**Comment by wyvernSemi** [comment]
Thank you for your debugging effort and accurate information. I don't know why I missed this in the code, as I do the correct thing in config.idle right beneath it.
